config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "cart", to: 'pages#cart', as: :cart
  get "drafts", to: 'pages#drafts', as: :drafts
  get "about", to: 'pages#about_us', as: :about_us
  get "instagram", to: 'pages#instagram', as: :instagram
  get "my_orders", to: 'pages#my_orders', as: :my_orders
  get "error_404", to: 'pages#error_404', as: :error_404
  resources :products, only: [:show] do
    resources :prints, only: [:new, :create]
    member do
      get "remember_product", to: 'products#remember_product', as: :remember
    end
  end
  resources :prints, only: [:edit, :update, :destroy] do
    collection do
      patch "upload_instagram", to: 'prints#upload_instagram', as: :upload_instagram
    end
    member do
      delete "trash/:key", to: 'prints#trash_pic', as: :trash
      get "remember_print", to: 'prints#remember_print', as: :remember
      patch :complete
    end
  end
  resources :orders, only: [:index, :show, :update] do
    collection do
      patch :add_item
    end
    member do
      patch :ship
      patch :pay
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/print.rb
class Print < ApplicationRecord
  belongs_to :order
  belongs_to :product

  has_one_attached :cover_photo
  has_many_attached :photos
end

app/controllers/prints_controller.rb
require "open-uri"

class PrintsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def new
    @product = Product.find(params[:product_id])
    @print = Print.new(product: @product)
    @new = true
    case @print.product.category
    when "book"
      render :book_editor
    when "frame"
      render :frame_editor
    when "photo"
      render :photo_editor
    end
  end

  def create
    @print = Print.new(print_params)
    @print.order = pending_order
    @print.product = Product.find(params[:product_id])
    if @print.save
      redirect_to edit_print_path(@print)
    else
      case @print.product.category
      when "book"
        render :book_editor
      when "frame"
        render :frame_editor
      when "photo"
        render :photo_editor
      end
    end
  end

  def edit
    @print = Print.find(params[:id])
    case @print.product.category
    when "book"
      render :book_editor
    when "frame"
      render :frame_editor
    when "photo"
      render :photo_editor
    end
  end

  def update
    @print = Print.find(params[:id])
    if print_params[:photos] || print_params[:cover_photo] || print_params[:title]
      @print.photos.attach(params[:print][:photos]) if params[:print][:photos].present?
      @print.cover_photo.attach(params[:print][:cover_photo]) if params[:print][:cover_photo].present?
      @print.save
      @print.update(title: print_params[:title])
      redirect_to edit_print_path(@print)
      # case @print.product.category
      # when "book"
      #   render :book_editor
      # when "frame"
      #   render :frame_editor
      # when "photo"
      #   render :photo_editor
      # end
    else
      case @print.product.category
      when "book"
        render :book_editor
      when "frame"
        render :frame_editor
      when "photo"
        render :photo_editor
      end
    end
  end

  def complete
    @print = Print.find(params[:id])
    @print.complete = true
    @print.save
    redirect_to cart_path
  end

  def destroy
    @print = Print.find(params[:id])
    @print.destroy
    redirect_to cart_path
  end

  def trash_pic
    @print = Print.find(params[:id])
    persisted_photos = @print.photos.reject {|photo| photo.key == params[:key]}
    persisted_photos_blob = persisted_photos.map {|photo| photo.blob}
    @print.photos.detach
    @print.photos.attach persisted_photos_blob
    redirect_to edit_print_path(@print)
  end

  def remember_print
    session[:remembered_print] = { new: false, id: params[:id] }
    redirect_to "https://api.instagram.com/oauth/authorize?client_id=1569528696781232&redirect_uri=https://0667-2001-1388-3c1-7520-c4af-9418-bf1a-d0eb.ngrok.io/instagram/&scope=user_profile,user_media&response_type=code"
  end

  def upload_instagram
    # byebug
    urls = params[:urls]
    if session[:remembered_print]["new"] == true
      product = Product.find(session[:remembered_print]["id"])
      print = Print.create(product: product, order: pending_order)
    else
      print = Print.find(session[:remembered_print]["id"])
    end
    urls.each do |url|
      file = URI.open(url)
      print.photos.attach(io: file, filename: "from_instagram", content_type: 'image/png')
    end
    print.save
    session[:remembered_print] = nil
    render json: { url: edit_print_url(print) }.to_json
  end

  private

  def print_params

    params.require(:print).permit(:product_id, :order_id, :title, :cover_photo, photos: [])
  end
end

app/views/prints/book_editor.html.erb
<!--- nuevo formato --->

<div class="container py-5">

    <!-- For demo purpose -->
    <header class="text-center">
        <h2 class="display-4"><%= @new ? "Crear" : "Editar" %> <%= @print.product.name %></h2>
    </header>


    <div class="row py-4">
        <div class="col-lg-12 mx-auto">

            <!-- Upload image input-->
            <div class="col-lg-6 mx-auto">
              <%= simple_form_for([@product, @print]) do |f| %>
              <%
=begin%>
 <div class="input-group mb-3 px-2 py-2 rounded-pill bg-white shadow-sm photo_editor">
                  <%= f.input :title, input_html: {class: "img-upload form-control border-0", placeholder: "Titulo" }, label: false %>
              </div>
<%
=end%>
              <%
=begin%>
 <%= f.input :title, label: "Qué título quieres poner?" %>
<%
=end%>

              <%# <div class="input-group mb-3 px-2 py-2 rounded-pill bg-white shadow-sm photo_editor">
                  <div class="input-group-append">
                      <label for="print_cover_photo" class="btn btn-light m-0 rounded-pill px-4"> <i class="fa fa-cloud-upload mr-2 text-muted"></i><small class="text-uppercase font-weight-bold text-muted">Elegir portada</small></label>
                  </div>
                  <%= f.input :cover_photo, as: :file, input_html: {class: "img-upload form-control border-0" }, label: "No se eligio portada", :label_html => { :class => 'font-weight-light text-muted upload-label', id: "print_cover_photo_label" } %>
              <%# </div>
              <div class="input-group mb-3 px-2 py-2 rounded-pill bg-white shadow-sm photo_editor">
                  <div class="input-group-append">
                      <label for="print_photos" class="btn btn-light m-0 rounded-pill px-4"> <i class="fa fa-cloud-upload mr-2 text-muted"></i><small class="text-uppercase font-weight-bold text-muted">Elegir fotos</small></label>
                  </div>
                  <%= f.input :photos, as: :file, input_html: { multiple: true, class: "img-upload form-control border-0" }, label: "No se eligieron fotos", :label_html => { :class => 'font-weight-light text-muted upload-label', id: "print_photos_label" } %>
              <%# </div> %>


              <%# <a href="https://api.instagram.com/oauth/authorize?client_id=1569528696781232&redirect_uri=https://0667-2001-1388-3c1-7520-c4af-9418-bf1a-d0eb.ngrok.io/instagram/&scope=user_profile,user_media&response_type=code" class="btn btn-flat d-block mb-5">Cargar de Instagram</a> %>
              <!-- Button trigger modal-->


            <button type="button" class="btn btn-flat btn-block mb-5" data-toggle="modal" data-target="#modalPush">Cargar fotos</button>


              <%# <% if @new %>
               <%#  <%= f.button :submit, "Crear #{@print.product.name}" , class: "btn btn-flat"%>
              <%# else %>
                <%#= f.button :submit, "Actualizar #{@print.product.name}" , class: "btn btn-flat"%>
              <%# end %>


            </div>


            <% end %>


<%# INICIO DE MODAL 1 %>


            <!--Modal: modalPush-->
            <div class="modal fade" id="modalPush" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
              aria-hidden="true">
              <div class="modal-dialog modal-notify modal-info" role="document">
                <!--Content-->
                <div class="modal-content text-center">
                  <!--Header-->
                  <div class="modal-header d-flex justify-content-center">
                    <p class="heading">Elige de donde traer tus fotos</p>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                  </div>

                  <!--Body-->
                  <div class="modal-body">

                     <% if @new %>
                        <%= link_to remember_product_path(@print.product) do %>
                          <img src="https://img.icons8.com/cute-clipart/64/000000/instagram-new.png" height="70"/>
                        <% end %>
                      <% else %>
                        <%= link_to remember_print_path(@print) do %>
                          <img src="https://img.icons8.com/cute-clipart/64/000000/instagram-new.png" height="70"/>
                        <% end %>
                      <% end %>

                    <a href=# data-dismiss="modal" data-toggle="modal" data-target="#modalPush2"><img src="https://img.icons8.com/fluency/48/000000/laptop.png" height="60"/></a>

                  </div>

                </div>
                <!--/.Content-->
              </div>
            </div>
            <!--Modal: modalPush-->


            <!--Modal: modalPush2-->
            <div class="modal fade" id="modalPush2" tabindex="5" role="dialog" aria-labelledby="exampleModalLabel"
              aria-hidden="true">
              <div class="modal-dialog modal-notify modal-info modal-lg" role="document">
                <!--Content-->
                <div class="modal-content text-center">
                  <!--Header-->
                  <div class="modal-header d-flex justify-content-center">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                  </div>

                  <!--Body-->
                  <div class="modal-body">


                    <div class="col-lg-12 mx-auto">
                      <%= simple_form_for([@product, @print]) do |f| %>
                        <%# <%= f.input :title, label: "Qué título quieres poner?" %>

                        <div class="input-group mb-3 px-2 py-2 rounded-pill bg-white shadow-sm photo_editor">
                            <div class="input-group-append">
                                <label for="print_cover_photo" class="btn btn-light m-0 rounded-pill px-4"> <i class="fa fa-cloud-upload mr-2 text-muted"></i><small class="text-uppercase font-weight-bold text-muted">Elegir portada</small></label>
                            </div>
                            <%= f.input :cover_photo, as: :file, input_html: {class: "img-upload form-control border-0" }, label: "No se eligio portada", :label_html => { :class => 'font-weight-light text-muted upload-label', id: "print_cover_photo_label" } %>
                        </div>
                        <div class="input-group mb-3 px-2 py-2 rounded-pill bg-white shadow-sm photo_editor">
                            <div class="input-group-append">
                                <label for="print_photos" class="btn btn-light m-0 rounded-pill px-4"> <i class="fa fa-cloud-upload mr-2 text-muted"></i><small class="text-uppercase font-weight-bold text-muted">Elegir fotos</small></label>
                            </div>
                            <%= f.input :photos, as: :file, input_html: { multiple: true, class: "img-upload form-control border-0" }, label: "No se eligieron fotos", :label_html => { :class => 'font-weight-light text-muted upload-label', id: "print_photos_label" } %>
                        </div>

                        <% if @new %>
                          <%= f.button :submit, "Crear #{@print.product.name}" , class: "btn btn-flat"%>
                        <% else %>
                          <%= f.button :submit, "Actualizar #{@print.product.name}" , class: "btn btn-flat"%>
                        <% end %>
                      <% end %>
                      </div>

                    </div>

                </div>
                <!--/.Content-->
              </div>
            </div>
            <!--Modal: modalPush2-->
<%# FIN DE MODAL 2 %>

            <% unless @new %>
              <div style="text-align: end">
                <%= link_to "Mandar al carrito", complete_print_path, method: :patch, class: "btn btn-flat" %>
              </div>
            <% end %>
            <!-- Uploaded image area-->

              <% if @print.photos.attached? || @print.cover_photo.attached? %>

                  <div class="photos mt-1 mb-5">
                    <% if @print.cover_photo.attached? %>
                      <div class="photo-container">
                        <div class="cover-photo-tag">Portada</div>
                        <%= cl_image_tag @print.cover_photo.key, class: "photo" %>

                            <i class="fas fa-trash-alt delete-photo-btn"></i>

                      </div>
                    <% end %>

                    <% @print.photos.each do |photo| %>
                      <div class="photo-container">
                        <%= cl_image_tag photo.key, class: "photo" %>
                        <%= link_to trash_print_path(key: photo.key), method: :delete do %>
                            <i class="fas fa-trash-alt delete-photo-btn"></i>
                        <% end %>
                      </div>
                    <% end %>
                  </div>

              <% end %>


        </div>
    </div>
</div>

<script>
// /*  ==========================================
//     SHOW UPLOADED IMAGE
// * ========================================== */
// function readURL(input) {
//     if (input.files && input.files[0]) {
//         var reader = new FileReader();

//         reader.onload = function (e) {
//           console.log(e)
//           $('#imageResult')
//                 .attr('src', e.target.result);
//         };
//         reader.readAsDataURL(input.files[0]);
//     }
// }

// (function () {
//     $('#upload').on('change', function () {
//         readURL(input);
//     });
// });

// /*  ==========================================
//     SHOW UPLOADED IMAGE NAME
// * ========================================== */
var input = document.getElementById( 'print_photos' );
var infoArea = document.getElementById( 'print_photos_label' );

input.addEventListener('change', showFilesNames);
function truncate(str, n){
  return (str.length > n) ? str.substr(0, n-1) + '...' : str;
};
function showFilesNames(e) {
  const input = e.srcElement;
  const files = Array.from(input.files).map(f => f.name).join();
  infoArea.textContent = truncate(files,30);
}

var cover_input = document.getElementById( 'print_cover_photo' );
var cover_infoArea = document.getElementById( 'print_cover_photo_label' );

cover_input.addEventListener('change', showFileName);

function showFileName(e) {
  const cover_input = e.srcElement;
  const file = cover_input.files[0].name;
  cover_infoArea.textContent = file;
}
</script>

app/views/prints/frame_editor.html.erb
<%
=begin%>
 <div class="container py-5">

    <!-- For demo purpose -->
    <header class="text-center">
        <h2 class="display-4"><%= @new ? "Crear" : "Editar" %> <%= @print.product.name %></h2>
    </header>


    <div class="row py-4">
        <div class="col-lg-12 mx-auto">

            <!-- Upload image input-->
            <div class="col-lg-6 mx-auto">
              <%= simple_form_for([@product, @print]) do |f| %>
              <div class="input-group mb-3 px-2 py-2 rounded-pill bg-white shadow-sm photo_editor">
                  <div class="input-group-append">
                      <label for="print_photos" class="btn btn-light m-0 rounded-pill px-4"> <i class="fa fa-cloud-upload mr-2 text-muted"></i><small class="text-uppercase font-weight-bold text-muted">Elegir fotos</small></label>
                  </div>
                  <%= f.input :photos, as: :file, input_html: { multiple: true, class: "img-upload form-control border-0" }, label: "No se eligieron fotos", :label_html => { :class => 'font-weight-light text-muted upload-label', id: "print_photos_label" } %>
              </div>
            <% if @new %>
              <%= f.button :submit, "Crear #{@print.product.name}" , class: "btn btn-flat"%>
            <% else %>
              <%= f.button :submit, "Actualizar #{@print.product.name}" , class: "btn btn-flat"%>
            <% end %>
            <% unless @new %>
              <%= link_to "Mandar al carrito", complete_print_path, method: :patch, class: "btn btn-flat" %>
            <% end %>
            </div>


            <% end %>



            <!-- Uploaded image area-->

              <% if @print.photos.attached? %>

                  <div class="photos">
                    <% @print.photos.each do |photo| %>
                      <div class="photo-container">
                        <%= cl_image_tag photo.key, class: "photo" %>
                        <%= link_to trash_print_path(key: photo.key), method: :delete do %>
                            <i class="fas fa-trash-alt delete-photo-btn"></i>
                        <% end %>
                      </div>
                    <% end %>
                  </div>

              <% end %>


        </div>
    </div>
</div>
<%
=end%>


<!--- nuevo formato --->

<div class="container py-5">

    <!-- For demo purpose -->
    <header class="text-center">
        <h2 class="display-4"><%= @new ? "Crear" : "Editar" %> <%= @print.product.name %></h2>
    </header>


    <div class="row py-4">
        <div class="col-lg-12 mx-auto">

            <!-- Upload image input-->
            <div class="col-lg-6 mx-auto">
              <%= simple_form_for([@product, @print]) do |f| %>
              <%
=begin%>
 <div class="input-group mb-3 px-2 py-2 rounded-pill bg-white shadow-sm photo_editor">
                  <%= f.input :title, input_html: {class: "img-upload form-control border-0", placeholder: "Titulo" }, label: false %>
              </div>
<%
=end%>
              <%
=begin%>
 <%= f.input :title, label: "Qué título quieres poner?" %>
<%
=end%>

              <%# <div class="input-group mb-3 px-2 py-2 rounded-pill bg-white shadow-sm photo_editor">
                  <div class="input-group-append">
                      <label for="print_cover_photo" class="btn btn-light m-0 rounded-pill px-4"> <i class="fa fa-cloud-upload mr-2 text-muted"></i><small class="text-uppercase font-weight-bold text-muted">Elegir portada</small></label>
                  </div>
                  <%= f.input :cover_photo, as: :file, input_html: {class: "img-upload form-control border-0" }, label: "No se eligio portada", :label_html => { :class => 'font-weight-light text-muted upload-label', id: "print_cover_photo_label" } %>
              <%# </div>
              <div class="input-group mb-3 px-2 py-2 rounded-pill bg-white shadow-sm photo_editor">
                  <div class="input-group-append">
                      <label for="print_photos" class="btn btn-light m-0 rounded-pill px-4"> <i class="fa fa-cloud-upload mr-2 text-muted"></i><small class="text-uppercase font-weight-bold text-muted">Elegir fotos</small></label>
                  </div>
                  <%= f.input :photos, as: :file, input_html: { multiple: true, class: "img-upload form-control border-0" }, label: "No se eligieron fotos", :label_html => { :class => 'font-weight-light text-muted upload-label', id: "print_photos_label" } %>
              <%# </div> %>


              <%# <a href="https://api.instagram.com/oauth/authorize?client_id=1569528696781232&redirect_uri=https://0667-2001-1388-3c1-7520-c4af-9418-bf1a-d0eb.ngrok.io/instagram/&scope=user_profile,user_media&response_type=code" class="btn btn-flat d-block mb-5">Cargar de Instagram</a> %>
              <!-- Button trigger modal-->


            <button type="button" class="btn btn-flat btn-block mb-5" data-toggle="modal" data-target="#modalPush">Cargar fotos</button>


              <%# <% if @new %>
               <%#  <%= f.button :submit, "Crear #{@print.product.name}" , class: "btn btn-flat"%>
              <%# else %>
                <%#= f.button :submit, "Actualizar #{@print.product.name}" , class: "btn btn-flat"%>
              <%# end %>


            </div>


            <% end %>


<%# INICIO DE MODAL 1 %>


            <!--Modal: modalPush-->
            <div class="modal fade" id="modalPush" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
              aria-hidden="true">
              <div class="modal-dialog modal-notify modal-info" role="document">
                <!--Content-->
                <div class="modal-content text-center">
                  <!--Header-->
                  <div class="modal-header d-flex justify-content-center">
                    <p class="heading">Elige de donde traer tus fotos</p>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                  </div>

                  <!--Body-->
                  <div class="modal-body">

                     <% if @new %>
                        <%= link_to remember_product_path(@print.product) do %>
                          <img src="https://img.icons8.com/cute-clipart/64/000000/instagram-new.png" height="70"/>
                        <% end %>
                      <% else %>
                        <%= link_to remember_print_path(@print) do %>
                          <img src="https://img.icons8.com/cute-clipart/64/000000/instagram-new.png" height="70"/>
                        <% end %>
                      <% end %>

                    <a href=# data-dismiss="modal" data-toggle="modal" data-target="#modalPush2"><img src="https://img.icons8.com/fluency/48/000000/laptop.png" height="60"/></a>

                  </div>

                </div>
                <!--/.Content-->
              </div>
            </div>
            <!--Modal: modalPush-->


            <!--Modal: modalPush2-->
            <div class="modal fade" id="modalPush2" tabindex="5" role="dialog" aria-labelledby="exampleModalLabel"
              aria-hidden="true">
              <div class="modal-dialog modal-notify modal-info modal-lg" role="document">
                <!--Content-->
                <div class="modal-content text-center">
                  <!--Header-->
                  <div class="modal-header d-flex justify-content-center">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                  </div>

                  <!--Body-->
                  <div class="modal-body">


                    <div class="col-lg-12 mx-auto">
                      <%= simple_form_for([@product, @print]) do |f| %>
                        <%# <%= f.input :title, label: "Qué título quieres poner?" %>

                        <div class="input-group mb-3 px-2 py-2 rounded-pill bg-white shadow-sm photo_editor">
                            <div class="input-group-append">
                                <label for="print_photos" class="btn btn-light m-0 rounded-pill px-4"> <i class="fa fa-cloud-upload mr-2 text-muted"></i><small class="text-uppercase font-weight-bold text-muted">Elegir fotos</small></label>
                            </div>
                            <%= f.input :photos, as: :file, input_html: { multiple: true, class: "img-upload form-control border-0" }, label: "No se eligieron fotos", :label_html => { :class => 'font-weight-light text-muted upload-label', id: "print_photos_label" } %>
                        </div>

                        <% if @new %>
                          <%= f.button :submit, "Crear #{@print.product.name}" , class: "btn btn-flat"%>
                        <% else %>
                          <%= f.button :submit, "Actualizar #{@print.product.name}" , class: "btn btn-flat"%>
                        <% end %>
                      <% end %>
                      </div>

                    </div>

                </div>
                <!--/.Content-->
              </div>
            </div>
            <!--Modal: modalPush2-->
<%# FIN DE MODAL 2 %>

            <% unless @new %>
              <div style="text-align: end">
                <%= link_to "Mandar al carrito", complete_print_path, method: :patch, class: "btn btn-flat" %>
              </div>
            <% end %>
            <!-- Uploaded image area-->

              <% if @print.photos.attached? %>

                  <div class="photos mt-1 mb-5">
                    <% @print.photos.each do |photo| %>
                      <div class="photo-container">
                        <%= cl_image_tag photo.key, class: "photo" %>
                        <%= link_to trash_print_path(key: photo.key), method: :delete do %>
                            <i class="fas fa-trash-alt delete-photo-btn"></i>
                        <% end %>
                      </div>
                    <% end %>
                  </div>

              <% end %>


        </div>
    </div>
</div>


<script>
var input = document.getElementById( 'print_photos' );
var infoArea = document.getElementById( 'print_photos_label' );

input.addEventListener('change', showFilesNames);
function truncate(str, n){
  return (str.length > n) ? str.substr(0, n-1) + '...' : str;
};
function showFilesNames(e) {
  const input = e.srcElement;
  const files = Array.from(input.files).map(f => f.name).join();
  infoArea.textContent = truncate(files,30);
}
</script>