config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "cart", to: 'pages#cart', as: :cart
  get "drafts", to: 'pages#drafts', as: :drafts
  get "about", to: 'pages#about_us', as: :about_us
  get "instagram", to: 'pages#instagram', as: :instagram
  get "my_orders", to: 'pages#my_orders', as: :my_orders
  get "error_404", to: 'pages#error_404', as: :error_404
  resources :products, only: [:show] do
    resources :prints, only: [:new, :create]
    member do
      get "remember_product", to: 'products#remember_product', as: :remember
    end
  end
  resources :prints, only: [:edit, :update, :destroy] do
    collection do
      patch "upload_instagram", to: 'prints#upload_instagram', as: :upload_instagram
    end
    member do
      delete "trash/:key", to: 'prints#trash_pic', as: :trash
      get "remember_print", to: 'prints#remember_print', as: :remember
      patch :complete
    end
  end
  resources :orders, only: [:index, :show, :update] do
    collection do
      patch :add_item
    end
    member do
      patch :ship
      patch :pay
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <div class="footer mt-auto row">
  <div class="footer-links col-md-6 col-sm-12">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright col-md-6 col-sm-12">
    Hecho con  <i class="fas fa-heart"></i> x Clau, Luis, Benja & Juanma
  </div>
</div> %>

  <!-- Site footer -->
<footer class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <h6>Holi</h6>
        <p class="text-justify">Instapixit es an iniciativa de amantes de la fotografía y las cosquillitas que compartirla trae.</p>
      </div>

      <div class="col-xs-6 col-md-2">
        <h6>Products</h6>
        <ul class="footer-links">
        <% @products.each do |product| %>
          <li><a href=<%= product_path(product)%>><%= product.name.split.first %></a></li>
        <% end %>
      </div>

      <div class="col-xs-6 col-md-4">
        <!-- Links -->
        <h6 class="text-uppercase fw-bold mb-4">
          Contact
        </h6>
        <p><i class="fas fa-home me-3"></i>Lima - Peru</p>
        <p>
          <i class="fas fa-envelope me-3"></i>
          holi@instapixit.com
        </p>
        <p><i class="fas fa-phone me-3"></i> + 51 234 567 88</p>
      </div>
    </div>
    <hr>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-6 col-xs-12">
        <p class="copyright-text">Copyright &copy; 2022 Todos los Derechos Reservados
      <a href="#">Instapixit</a>.
        </p>
      </div>

      <div class="col-md-4 col-sm-6 col-xs-12">
        <ul class="social-icons">
          <li><a class="facebook" href="#"><i class="fab fa-facebook-f"></i></a></li>
          <li><a class="twitter" href="#"><i class="fab fa-twitter"></i></a></li>
          <li><a class="linkedin" href="#"><i class="fab fa-linkedin"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
     <img src="https://res.cloudinary.com/dsxmae0xw/image/upload/v1644455044/instapix-chinoa-assets/logo/logo4_qvfg2f.svg" alt="instapixit" class="navbar-logo">
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Admin", orders_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "My Orders", my_orders_path, class: "nav-link" %>
          </li>


          <li class="nav-item">
            <%= link_to drafts_path, class: "nav-link cart-link"  do %>
              <i class="fas fa-edit"></i>
              <% if print_drafts.any? %>
                <span class="nav-counter"><%= print_drafts.count %></span>
              <% end %>
            <% end %>
          </li>

          <li>
            <%= link_to cart_path, class: "nav-link cart-link"  do %>
              <i class="fas fa-shopping-cart"></i>
              <% if pending_order.prints.where(complete: true).any? %>
                <span class="nav-counter"><%= pending_order.prints.where(complete: true).count %></span>
              <% end %>
            <% end %>
          </li>
          <li class="nav-item">
            <%#= link_to "My coworkings", my_coworkings_path, class: "nav-link" %>
          </li>
          <%# <a class="btn btn-flat mr-3" href="#">Comenzar</a> %>
          <li class="nav-item dropdown">
            <% if current_user && current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://toppng.com/uploads/preview/user-account-management-logo-user-icon-11562867145a56rus2zwu.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%#= link_to "Action", "#", class: "dropdown-item" %>
              <%#= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <li>
        <% end %>
      </ul>
    </div>
  </div>
</div>