config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "cart", to: 'pages#cart', as: :cart
  get "drafts", to: 'pages#drafts', as: :drafts
  get "about", to: 'pages#about_us', as: :about_us
  get "instagram", to: 'pages#instagram', as: :instagram
  get "my_orders", to: 'pages#my_orders', as: :my_orders
  get "error_404", to: 'pages#error_404', as: :error_404
  resources :products, only: [:show] do
    resources :prints, only: [:new, :create]
    member do
      get "remember_product", to: 'products#remember_product', as: :remember
    end
  end
  resources :prints, only: [:edit, :update, :destroy] do
    collection do
      patch "upload_instagram", to: 'prints#upload_instagram', as: :upload_instagram
    end
    member do
      delete "trash/:key", to: 'prints#trash_pic', as: :trash
      get "remember_print", to: 'prints#remember_print', as: :remember
      patch :complete
    end
  end
  resources :orders, only: [:index, :show, :update] do
    collection do
      patch :add_item
    end
    member do
      patch :ship
      patch :pay
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/cart.html.erb
<%
=begin%>
 <div class="container">
    <h2>Carrito <i class="fas fa-shopping-cart"></i></h2>

    <div class="row">
      <div class="col-md-6 col-xs-12">
        <div class="card mr-2 p-3">
          <h3>Enviar</h3>
          <%= simple_form_for @order, url: ship_order_path(@order), method: :patch do |f| %>
            <div class="form-inputs">
              <%= f.input :shipping_address,
                          required: true,
                          autofocus: true,
                          input_html: { id: 'shipping_address'} %>
            </div>
            <div class="form-actions">
              <%= f.button :submit, "Confirmar direccion", class: "btn btn-flat" %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="col-md-6 col-xs-12">
        <div class="card p-3">
          <ul>
            <% @order.prints.where(complete: true).each do |print| %>
              <li><%= print.id %> - <%= print.product.name %> x <%= print.quantity %> unidades - S/<%= print.product.base_price %>
                  <%= link_to "Editar", edit_print_path(print) %>
                  <%= link_to "Eliminar", print_path(print), method: :delete %>
              </li>
            <% end %>
              <% if @order.prints.where(complete: true).any? %>
                <%= link_to "Pagar", pay_order_path(@order), method: :patch class: "btn btn-flat" %>
              <% end %>
          </ul>
        </div>
      </div>
    </div>


</div>
<%
=end%>


<% if @order.prints.where(complete: true).any? %>

<div class="px-4 px-lg-0">
  <!-- For demo purpose -->
  <div class="container py-5 text-center">
    <h1 class="display-4">Carrito</h1>
  </div>
  <!-- End -->

  <div class="pb-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 p-5 bg-white rounded shadow-sm mb-5">

          <!-- Shopping cart table -->
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" class="border-0 bg-light">
                    <div class="p-2 px-3 text-uppercase">Producto</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Precio</div>
                  </th>
                  <th scope="col" class="border-0 bg-light text-center">
                    <div class="py-2 text-uppercase">Cantidad</div>
                  </th>
                  <th scope="col" class="border-0 bg-light text-center">
                    <div class="py-2 text-uppercase ">Remover</div>
                  </th>
                </tr>
              </thead>
              <tbody>
                <% @order.prints.where(complete: true).each do |print| %>
                  <tr>
                    <th scope="row" class="border-0">
                      <div class="p-2 d-flex">
                      <% if print.cover_photo.attached? %>
                        <div class="cart-photo shadow-sm" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path print.cover_photo.key, crop: :fill %>')"></div>
                       <% elsif print.photos.attached? %>
                        <div class="cart-photo shadow-sm" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path print.photo[0].key, crop: :fill %>')"></div>
                      <% else %>
                        <div class="cart-photo shadow-sm" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://source.unsplash.com/1600x900/?photo+album/1')"></div>
                      <% end %>
                        <div class="ml-3 d-inline-block align-middle">
                          <h5 class="mb-0"> <a href="#" class="text-dark d-inline-block align-middle"><%= print.product.name %></a></h5><span class="text-muted font-weight-normal font-italic d-block">Categoría: <%= print.product.category %></span>
                        </div>
                      </div>
                    </th>
                    <td class="border-0 align-middle"><strong>S/.<%= number_with_precision(print.product.base_price, precision: 2) %></strong></td>
                    <td class="border-0 align-middle text-center"><strong><%= print.quantity %></strong></td>
                    <td class="border-0 align-middle text-center">
                      <%= link_to print_path(print), method: :delete, remote: true  do %>
                        <i class="fa fa-trash text-dark"></i>
                      <% end %>
                    </td>
                  </tr>
                <% end %>

              </tbody>
            </table>
          </div>
          <!-- End -->
        </div>
      </div>

      <div class="row py-5 p-4 bg-white rounded shadow-sm" data-controller="ship-pay-order">

        <div class="col-lg-6">

          <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Cupón de descuento</div>
          <div class="p-4">
            <div class="input-group mb-4 border rounded-pill p-2">
              <input type="text" placeholder="Apply coupon" aria-describedby="button-addon3" class="form-control border-0">
              <div class="input-group-append border-0">
                <button id="button-addon3" type="button" class="btn btn-dark px-4 rounded-pill btn-flat" data-action='click->ship-pay-order#coupon'><i class="fa fa-gift mr-2"></i>Aplicar</button>
              </div>
            </div>
            <span class="text-secondary d-none" data-ship-pay-order-target="coupon">Codigo inválido</span>
          </div>


          <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Dirección</div>
          <div class="p-4">
            <%= simple_form_for @order, url: ship_order_path(@order), remote: true,
            data: { ship_pay_order_target: 'form'}, method: :patch do |f| %>
              <div class="input-group mb-4 border rounded-pill p-3">
                <%= f.input :shipping_address,
                            required: true,
                            autofocus: true,
                            label: false,
                            input_html: { id: 'shipping_address', class: 'form-control border-0', placeholder: "Dirección"} %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="col-lg-6">
          <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Resumen</div>
          <div class="p-4">
            <ul class="list-unstyled mb-4">
              <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Subtotal </strong><strong>S/<%= (@total_price/1.18).round(2) %></strong></li>
              <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Costo de envío</strong><strong>S/.5.00</strong></li>
              <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">IGV</strong><strong>S/.<%= (@total_price - (@total_price/1.18).round(2)).round(2)%></strong></li>
              <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Total</strong>
                <h5 class="font-weight-bold">S/<%= number_with_precision(@total_price, precision: 2) %></h5>
              </li>
            </ul><button  id="sweet-alert-demo" type="submit" class="btn btn-dark rounded-pill py-2 btn-block btn-flat" data-action='click->ship-pay-order#send'>Enviar orden</button>
            <%# <button id="sweet-alert-demo" class="btn btn-danger">Delete</button> %>
            <%= link_to "", root_path, id: "payment-link", class: "hidden" %>
          </div>
        </div>



      </div>

    </div>
  </div>
</div>

<% else %>

<% end %>


<script>
  // const shipping_form = document.getElementById('edit_order_17')
  // console.log(shipping_form)
</script>

app/views/pages/drafts.html.erb
<div class="container width-session">
  <div class="card m-5 py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 col-xs-12">
        <h2>En proceso</h2>
        <div class="cards mt-5">
          <% @prints.each do |print| %>
            <%= link_to edit_print_path(print) do %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3),
              rgba(0,0,0,0.3)), url('<%=
              if print.cover_photo.attached?
                cl_image_path print.cover_photo.key
              elsif print.photos.attached?
                cl_image_path print.photos[0].key
              else
                'https://source.unsplash.com/1600x900/?photos/1'
              end
              %>')">
                <%= print.product.name %>
              </div>
            <% end %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/error_404.html.erb
<body id="fondo">
  <div class="maestro d-flex justify-content-around pb-5">
    <div class="camera">
      <img class="brokencamera" src="https://res.cloudinary.com/deavmhgtx/image/upload/v1644427583/camerabroken_fewb7h.png" alt="">
    </div>
    <div class="text">
        <h1 class= "errornum"> 404</h1>
        <h2>Page Not Found</h2>
        <p> Please try one of the following pages</p>
        <a class="btn btn-flat" href="#">Back home</a>
    </div>
  </div>
</body>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1497030947858-3f40f1508e84?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80);">
  <div class="container text-center">
    <h1>Tus recuerdos al instante <strong></strong></h1>
    <p>Instapixit la forma más fácil de imprimir tus fotos</p>
    <%# <a class="btn btn-flat" href="#">Comenzar</a> %>
  </div>
</div>

  <div class="container">

    <div class="cards-container mb-5">
      <div>
        <div class="section-header">
          <h2 class="my-5 pl-5">¿Por qué Instapixit?</h2>
        </div>
        <div class="cards px-5">
          <div class="card-trip">
            <div class="card-trip-infos">
              <div class="text-center px-5">
                <h1 class="icono-camara d-flex justify-content-center fas fa-camera-retro" ></h1>
                <h4>Simple</h4>
                <h6 >Sube tus fotos desde el ordenador</h6>
              </div>
            </div>
          </div>
          <div class="card-trip">
            <div class="card-trip-infos">
              <div class="text-center px-3">
                <div class="img-cards">
                  <img src="https://res.cloudinary.com/deavmhgtx/image/upload/v1643930199/icon-cuadro_c1niph.png" style="width: 60px; height :60px; " alt="espejo">
                </div>
                <h4>Lindo</h4>
                <h6>Diseños increibles prearmados</h6>
              </div>
            </div>
          </div>
          <div class="card-trip">
            <div class="card-trip-infos">
              <div class="text-center px-5">
                <h1 class="icono-camara d-flex justify-content-center far fa-images " ></h1>
                <h4>Rápido</h4>
                <h6>Recibe tu pedido a tu casa</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="cards-container mb-5">
      <div>
        <div class="section-header">
          <h2 class="mb-5 pl-5">Elige tu producto</h2>
        </div>
        <div class="cards px-5">
          <% @products.each do |product| %>
            <div class="card-trip">
              <% if product.photo.present? %>
                <%= cl_image_tag product.photo.key %>
              <% else %>
                <img src="https://source.unsplash.com/1600x900/?photos/<%= rand(1..30) %>" />
              <% end %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= product.name%></h2>
                </div>
                <%# <h2 class="card-trip-pricing">S/.<%= product.base_price %></h2>
                <h2 class="price-tag">S/.<%= number_with_precision(product.base_price, precision: 2)%></h2>
              </div>
              <div class="card-trip-btns-container">
                <%= link_to "Empezar", new_product_print_path(product), class: "btn btn-flat" %>
                <%= link_to "Mas info", product_path(product), class: "btn btn-flat" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="cards-container mb-5">
      <div>
        <div class="section-header">
          <h2 class="my-5 pl-5">¿Qué dice la gente?</h2>
        </div>


          <div class="row mx-md-5">
            <div class="col-12 col-md-6">

                <div class="card-home" style ="width: 350px;">
                  <div class="d-flex">
                    <div class="text-center pt-3">
                      <h5><strong>Fotos preciosas en segundos</strong></h5>
                      <p class="nombre">MARIA GUEVARA</p>
                      <p class="carrera">Abogada</p>
                    </div>
                    <div class="card-violeta">
                      <img src="https://res.cloudinary.com/deavmhgtx/image/upload/v1643987382/maria-guevara_gtuw9r.jpg">
                    </div>
                  </div>
                </div>

              </div>

                <div class="col-12 col-md-6">

                  <div class="d-flex justify-content-end">
                    <div class="card-home" style ="width: 350px;">
                      <div class="d-flex">
                        <div class="text-center pt-3 px-3">
                          <h5><strong>Que liiindos books, amo!</strong></h5>
                          <p class="nombre">KATTY MELGAR</p>
                          <p class="carrera">Diseñadora</p>
                        </div>
                        <div class="card-violeta">
                          <img src="https://res.cloudinary.com/deavmhgtx/image/upload/v1643987383/katty-melgar_nruk69.jpg">
                        </div>
                      </div>
                    </div>
                  </div>




                </div>

            </div>
      </div>
    </div>

  </div>

app/views/pages/instagram.html.erb
  <div class="container">

    <button id="instagram-btn" class="btn btn-flat">Mandar fotos</button>

    <%
=begin%>
 <%= simple_form_for(url: upload_instagram_prints_path, method: :patch) do |f| %>
      <%= f.hidden :urls %>
      <%= f.button "Volver a print":submit, class: "btn-primary" %>
    <% end %>
<%
=end%>



    <% if current_user && current_user.instagram_auth_code %>
      <div class="photos mt-5">
        <% @pages.each do |page| %>
          <% page.payload.data.each do |post| %>
            <div class="photo-container">
              <img src="<%= post["media_url"] %>" class="photo" alt="">
                <i class="fas fa-solid fa-check check-btn"></i>
              <%= link_to "#", method: :patch do %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>



<script>
  photos = [];
  const checks = document.querySelectorAll(".check-btn");
  const btn = document.querySelector("#instagram-btn");
  checks.forEach( check => {
    check.addEventListener('click', () => {
      check.classList.toggle("green")
      const photo = check.parentElement.querySelector('.photo')
      photo.classList.toggle("selected")
      // photos.includes(photo.src) ? photos.filter(src => src !== photo.src) : photos.push(photo.src)
      // console.log(photos)
  })});
  btn.addEventListener('click', () => {
    document.querySelectorAll(".photo.selected").forEach(photo =>  {
      photos.push(photo.src)
    })
    console.log(photos)
    console.log("<%= upload_instagram_prints_url %>")
    fetch("<%= upload_instagram_prints_url %>", {
            method: 'PATCH',
            body: JSON.stringify({
              urls: photos,
            }),
            headers: {
              'Content-type': 'application/json; charset=UTF-8',
            },
          })
        .then((response) => response.json())
        .then((json) => window.location.replace(json.url));

  })
</script>

app/views/pages/my_orders.html.erb
<div class="container vh-100 py-2">

  <div class="container-fluid">
    <div class="row-fluid p-5 mt-4 bg-white">
        <div class="span8 well">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                  <a class="nav-link active" href="#home" data-target="#orders" data-toggle="tab">1 Todos </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#home" data-target="#paids" data-toggle="tab">2 Pagado </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#home" data-target="#printings" data-toggle="tab">3 En Impresión </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#home" data-target="#delivers" data-toggle="tab">4 Listo para enviar </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#home" data-target="#delivered" data-toggle="tab">5 Entregado </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#home" data-target="#cancelled_orders" data-toggle="tab">6 Cancelado </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active fade in show" id="orders">
                  <h3 class="py-3">Todas las órdenes</h3>
                  <table class="table">
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Direccion</th>
                        <th scope="col">Monto</th>
                        <th scope="col">Fecha de compra</th>
                        <%
=begin%>
 <th scope="col">Detalles</th>
<%
=end%>
                      </tr>
                    <% @orders.each do |order| %>
                      <tr>
                        <td><%= order.id %> </td>
                        <td><%= order.state %></td>
                        <td><%= order.shipping_address %></td>
                        <td><%= order.total_price %></td>
                        <td><%= order.purchase_date.strftime("%Y %m %d") %></td>
                        <%
=begin%>
 <td><%= link_to "Ver", order_path(order) %></td>
<%
=end%>
                      </tr>
                    <% end %>
                  </table>
                </div>


                <div class="tab-pane" id="paids">
                  <h3 class="py-3">Ordenes pagadas</h3>
                  <table class="table">
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Direccion</th>
                        <th scope="col">Monto</th>
                        <th scope="col">Fecha de compra</th>
                        <%
=begin%>
 <th scope="col">Detalles</th>
<%
=end%>
                      </tr>
                    <% @paids.each do |order| %>
                      <tr>
                        <td><%= order.id %> </td>
                        <td><%= order.state %></td>
                        <td><%= order.shipping_address %></td>
                        <td><%= order.total_price %></td>
                        <td><%= order.purchase_date %></td>
                        <%
=begin%>
 <td><%= link_to "Ver", order_path(order) %></td>
<%
=end%>
                      </tr>
                    <% end %>
                  </table>
                </div>

                <div class="tab-pane" id="printings">
                  <h3 class="py-3">Ordenes impresas</h3>
                  <table class="table">
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Direccion</th>
                        <th scope="col">Monto</th>
                        <th scope="col">Fecha de compra</th>
                        <%
=begin%>
 <th scope="col">Detalles</th>
<%
=end%>
                      </tr>
                    <% @printings.each do |order| %>
                      <tr>
                        <td><%= order.id %> </td>
                        <td><%= order.state %></td>
                        <td><%= order.shipping_address %></td>
                        <td><%= order.total_price %></td>
                        <td><%= order.purchase_date %></td>
                        <%
=begin%>
 <td><%= link_to "Ver", order_path(order) %></td>
<%
=end%>
                      </tr>
                    <% end %>
                  </table>
                </div>

                <div class="tab-pane" id="delivers">
                  <h3 class="py-3">Ordenes para entregar</h3>
                  <table class="table">
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Direccion</th>
                        <th scope="col">Monto</th>
                        <th scope="col">Fecha de compra</th>
                        <%
=begin%>
 <th scope="col">Detalles</th>
<%
=end%>
                      </tr>
                    <% @delivers.each do |order| %>
                      <tr>
                        <td><%= order.id %> </td>
                        <td><%= order.state %></td>
                        <td><%= order.shipping_address %></td>
                        <td><%= order.total_price %></td>
                        <td><%= order.purchase_date %></td>
                        <%
=begin%>
 <td><%= link_to "Ver", order_path(order) %></td>
<%
=end%>
                      </tr>
                    <% end %>
                  </table>
                </div>

                <div class="tab-pane" id="delivered">
                  <h3 class="py-3">Ordenes entregadas</h3>
                  <table class="table">
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">State</th>
                        <th scope="col">Direccion</th>
                        <th scope="col">Monto</th>
                        <th scope="col">Fecha de compra</th>
                        <%
=begin%>
 <th scope="col">Detalles</th>
<%
=end%>
                      </tr>
                    <% @delivered.each do |order| %>
                      <tr>
                        <td><%= order.id %> </td>
                        <td><%= order.state %></td>
                        <td><%= order.shipping_address %></td>
                        <td><%= order.total_price %></td>
                        <td><%= order.purchase_date %></td>
                        <%
=begin%>
 <td><%= link_to "Ver", order_path(order) %></td>
<%
=end%>
                      </tr>
                    <% end %>
                  </table>
                </div>

                </div>


            </div>
        </div>
    </div>
  </div>



</div>

app/views/pages/shipping.html.erb
<div class="container width-session">
  <div class="card m-2 p-5 mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6 col-xs-12 ju">
        <h3>Enviar</h3>
        <%= simple_form_for @order, url: ship_order_path(@order), method: :patch do |f| %>
        <div class="form-inputs">
          <%= f.input :shipping_address,
                      required: true,
                      autofocus: true,
                      input_html: { id: 'shipping_address'} %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Pagar", class: "btn btn-flat" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>